### PR TITLE
SUP-1681: Webhook event type definition for struct literal creation

### PR DESCRIPTION
**Pull request by james2791**
Feat (Webhook event types): Webhook event type definitions for allowing creation via struct literals

PR checklist:
- [ ] tests added -> (All pipeline template interaction with the REST API) -> *Tests consistent*
- [ ] examples of each service action (List, Get etc) added to the relevant `examples/` folder -> **No services altered**
- [x] `CHANGELOG.md` updated with pending release information

In previous version of Go-Buildkite; the `type`s of agent, build, job webhook events were created as structs without inner field exporting; meaning that instances of these types couldn't be created in a struct literal manner. A instance of the base type was required _first_ before adding its sub-fields:

```
jobFinishedEvent := buildkite.JobFinishedEvent{}
jobFinishedEvent.Pipeline = &buildkite.Pipeline{
	Name: buildkite.String("Android App"),
	... additional fields ...
}
```

This PR exports the inner types so that instances can be struct literal created while also keeping the above consuming model above in place - for example:

```
jobFinishedEvent := buildkite.JobFinishedEvent{
	JobEvent: buildkite.JobEvent{
		Pipeline: &buildkite.Pipeline{
			Name: buildkite.String("Android App"),
		},
		Build: ...
		Job: ...
	},
}
```

Addresses #170

### CODE REVIEW

**Comment by mcncl** [comment]
This change also means that the aliased types cannot have their own fields, they must use all and only the fields of their "event" types.

**Comment by mcncl** [comment]
Would require a `major` bump due to lack of backwards compatibility.

**Review by jradtilbrook — COMMENTED** [review]
What if we just exported the inner fields so they could be accessed? I don't know if keeping them private is that useful

**Comment by james2791** [comment]
👆

How about typed exporting - similar to what I had implemented [first](https://github.com/buildkite/go-buildkite/pull/175/commits/f1a978bd0fc8b2eff38fbc7988f7e1d2df39602a)? It would keep functionality, Im not too sure on why they were privatised in the beginning (minus exporting the base `AgentEvent` etc)

**Comment by jradtilbrook** [comment]
Yeah I think that seems okay. And that should be backwards compatible as well right?

**Comment by james2791** [comment]
Correct - same process in creating these struct instances as before; export just gives the chance to create them with the inner fields. Thankfully its not a drastic type change that would need to constitute a `x.0.0` release 👍

**Review by jradtilbrook — APPROVED** [review]

**Pull request merged**
