### PR TITLE
Add tags field to pipeline object

### PR DESCRIPTION
**Pull request by DeanBruntThirdfort**

### CODE REVIEW

**Comment by james2791** [comment]
Hey @DeanBruntThirdfort 👋

Thanks for the PR - tags addition to the pipeline creation/updates looks good to me (also tested on my side also).

Feel free to add a changelog entry as per the upcoming [PR](https://github.com/buildkite/go-buildkite/pull/148) for noting this contribution!

**Comment by DeanBruntThirdfort** [comment]
> Hey @DeanBruntThirdfort 👋
> 
> Thanks for the PR - tags addition to the pipeline creation/updates looks good to me (also tested on my side also).
> 
> Feel free to add a entr into the `Unreleased` section of the Changelog as per the upcoming [PR](https://github.com/buildkite/go-buildkite/pull/148) for noting your contribution!

Thanks!
I've added a changelog entry

**Comment by james2791** [comment]
Cheers @DeanBruntThirdfort 👍

Shall be included in the next release

**Comment by james2791** [comment]
Amazing @DeanBruntThirdfort 👍

Will be in the next release - thanks once again for your contribution!

**Review by james2791 — APPROVED** [review]
LGTM

**Pull request merged**
