### PR TITLE
Changes for v2

### PR DESCRIPTION
**Pull request by lox**
This PR moves to using the v2 of the Buildkite API as well as moving from projects to pipelines.

### CODE REVIEW

**Comment by lox** [comment]
@toolmantim @wolfeidau is this a good point to move this over to the buildkite org?

**Comment by toolmantim** [comment]
Woo! Yeah I can do this if @wolfeidau adds me as an admin

**Comment by wolfeidau** [comment]
@toolmantim I have added you but I think this is just for push access.

**Comment by wolfeidau** [comment]
@toolmantim I can transfer this to you and then you can push it to buildkite if you like.

**Comment by toolmantim** [comment]
@wolfeidau I think you might need to do that

**Comment by toolmantim** [comment]
@lox merge when ready!

**Comment by lox** [comment]
Done, tag away good sir.

**Comment by wolfeidau** [comment]
OK updated the version number and tagged https://github.com/buildkite/go-buildkite/releases/tag/v2.0.0 

Just need to tweak the readme.

**Pull request merged**
