### PR TITLE
Create pipeline

### PR DESCRIPTION
**Pull request by mubeta06**
And some other verb support i.e. Get and Delete.

### CODE REVIEW

**Comment by lox** [comment]
Sorry for the delay @mubeta06! This looks great, I'm just going through it now.

**Comment by mubeta06** [comment]
Oh yeah I forgot about this. I added support for other verbs on our fork too to support the terraform provider we are developing.

**Comment by lox** [comment]
Shall we consolidate on #21?

**Comment by mubeta06** [comment]
Yeah for sure!

**Pull request closed without merging**
